### ISSUE TITLE
Platform Request: Support Niche Video Game OS

### ISSUE THREAD

**Issue by VICTORVICKIE** [tsoding/raylib.js#11]
It would be nice to have support for a niche operating system like Windows, so devs like me who use it can contribute to this project.
but that would make `build.sh` and `build.bat` to be potentially out of sync, can I attempt to use `nob.c` for raylib.js

Note: I can work with WSL, if the project wants to be just Linux only.

![image](https://github.com/tsoding/raylib.js/assets/45727291/a6817f6c-2572-4167-aed6-79f2de0df2cc)

**Comment by VICTORVICKIE** [comment]
Oh now I get why this niche os sucks. wasm setup is a nightmare

**Comment by rexim** [comment]
I'll add the nob build myself. Thank you for filing this issue!

**Comment by VICTORVICKIE** [comment]
> I'll add the nob build myself. Thank you for filing this issue!

Oh, I have made a PR, if it needs work to meet any requirement, please do let me know
